//
//  ClassData.swift
//
//
//  Created by Garry Pettet on 07/11/2023.
//
//  Stores data about the class currently being compiled.

import Foundation

public class ClassData {
    
    // MARK: - Properties
    
    /// The class declaratation statement generated by the parser.
    public let declaration: ClassDeclStmt
    
    /// The number of instance fields created by this class.
    public var fieldCount: Int { return fields.count }
    
    /// The index in `fields` that fields belonging to instances of this class start at.
    /// Earlier indexes are used by classes further up the class hierarchy.
    public let fieldStartIndex: Int
    
    /// The names of all instance fields created by this class in the order they are created.
    public var fields: [String] = []
    
    /// The name of this class.
    public var name: String { return declaration.name }
    
    /// Optional data about this class's superclass.
    public let superclass: ClassData?
    
    /// The total number of fields used by this class and its entire hierarchy.
    public var totalFieldCount: Int { return fieldStartIndex + fieldCount }
    
    // MARK: - Methods
    
    public init(declaration: ClassDeclStmt, superclass: ClassData?) {
        self.declaration = declaration
        
        self.superclass = superclass
        if superclass == nil {
            fieldStartIndex = 0
        } else {
            fieldStartIndex = self.superclass!.fieldStartIndex + self.superclass!.fieldCount
        }
    }
}
